apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-runner-gha-rs-no-permission
  namespace: arc-runners
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-listener-sa
  namespace: arc-systems
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: karmada-listener-arc-patch
  namespace: arc-runners
rules:
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - patch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  - ephemeralrunners/status
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: karmada-listener-arc-patch
  namespace: arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: karmada-listener-arc-patch
subjects:
- kind: ServiceAccount
  name: karmada-listener-sa
  namespace: arc-systems
